server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true   # habilita integración con Eureka
              lower-case-service-id: true  # opcional, útil con Eureka
          routes:
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/categoria/**
