server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms_catalogo
              uri: lb://ms_catalogo
              predicates:
                - Path=/categoria/**
              # Si tu servicio real no expone /categoria/...:
              # filters:
              #   - StripPrefix=1
